# Infra local OrderFlow
# docker compose up -d

services:
  # Postgres — 4 DBs (auth, catalog, orders, inventory)
  postgres:
    image: postgres:16-alpine
    container_name: orderflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-orderflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-orderflow_secret}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-orderflow}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redpanda (Kafka sin Zookeeper)
  redpanda:
    image: redpandadata/redpanda:v24.2.4
    container_name: orderflow-redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      # PLAINTEXT = red de Docker | OUTSIDE = localhost desde el PC
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092"
      - "19092:19092"
      - "9644:9644"
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (más adelante)
  redis:
    image: redis:7-alpine
    container_name: orderflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Mailhog — emails fake en http://localhost:8025
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: orderflow-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
